In [1]:


import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv("insurance.csv")


In [3]:
print(df.head())

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86


In [4]:
cols = ["sex","smoker","region"]

for col in cols:
    df[col] = df[col].replace({"male":0,"female":1,"yes":1,"no":0,"southwest":1,"southeast":2,"northwest":3,"northeast":4})

print(df.head())

   age sex   bmi  children smoker region  expenses
0   19   1  27.9         0      1      1  16884.92
1   18   0  33.8         1      0      2   1725.55
2   28   0  33.0         3      0      2   4449.46
3   33   0  22.7         0      0      3  21984.47
4   32   0  28.9         0      0      3   3866.86


In [5]:

X = df.drop("expenses", axis = 1)
y = df["expenses"]

df = df.values
X = X.values
y= y.values

df
X
y

array([16884.92,  1725.55,  4449.46, ...,  1629.83,  2007.95, 29141.36],
      shape=(1338,))

In [6]:
X_max = X.max(axis = 0)
X_min = X.min(axis = 0)

X_norm = (X - X_min)/(X_max - X_min)

print(X_norm)

[[0.021739130434782608 1.0 0.320754716981132 0.0 1.0 0.0]
 [0.0 0.0 0.47978436657681933 0.2 0.0 0.3333333333333333]
 [0.21739130434782608 0.0 0.4582210242587601 0.6 0.0 0.3333333333333333]
 ...
 [0.0 1.0 0.5633423180592991 0.0 0.0 0.3333333333333333]
 [0.06521739130434782 1.0 0.2641509433962264 0.0 0.0 0.0]
 [0.9347826086956522 1.0 0.3530997304582211 0.0 1.0 0.6666666666666666]]


In [7]:
y_max = y.max()
y_min = y.min()

y_norm = (y - y_min)/(y_max - y_min)

print(y_norm)

[0.25161073 0.00963598 0.05311519 ... 0.00810809 0.01414366 0.44724875]


In [8]:
m,n = X.shape
print(n)

w = np.zeros(n)
b=0
a=0.01
itr = 1000





6


In [9]:
for i in range(itr):
    f_wb = np.dot(X_norm,w)+b

   
    dj_dw = np.zeros(n)
    dj_db = 0

    for j in range(m):
        error = f_wb[j] - y_norm[j]
        dj_db += error 

        for k in range(n):
            dj_dw[k] += error*X_norm[j][k]

    dj_dw = dj_dw/m
    dj_db = dj_db/m

    w -= a*dj_dw
    b -= a*dj_db




     

In [10]:
print("Optimised w: ",w)
print("Optimised b: ",b)




Optimised w:  [ 0.12123341 -0.01060073  0.06587578  0.02524451  0.30380778  0.00587058]
Optimised b:  0.05094633177411553


In [11]:
test_case = [19,0,30.1,4,1,1]
test_case_norm = (test_case - X_min)/ (X_max -X_min)

prediction = np.dot(test_case_norm,w) +b


final = prediction *(y_max - y_min) + y_min

print("\nPredicted value: ", final)


Predicted value:  26345.53177765156
