In [52]:
import pandas as pd
import numpy as np

In [53]:
df = pd.read_csv("Boston.csv")

print(df.head())

   Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0           1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1           2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2           3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3           4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4           5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   

   tax  ptratio   black  lstat  medv  
0  296     15.3  396.90   4.98  24.0  
1  242     17.8  396.90   9.14  21.6  
2  242     17.8  392.83   4.03  34.7  
3  222     18.7  394.63   2.94  33.4  
4  222     18.7  396.90   5.33  36.2  


In [54]:
X = df.drop(["medv","Unnamed: 0"], axis = 1).values
y = df["medv"].values

print(X)
print(y)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

In [55]:
X_max = X.max(axis=0)
X_min = X.min(axis=0)
y_max = y.max()
y_min = y.min()

def normalise(data):
    data_norm = (data - data.min(axis=0))/(data.max(axis=0)-data.min(axis=0))
    return data_norm



In [56]:
X_norm = normalise(X)
print(X_norm)

[[0.00000000e+00 1.80000000e-01 6.78152493e-02 ... 2.87234043e-01
  1.00000000e+00 8.96799117e-02]
 [2.35922539e-04 0.00000000e+00 2.42302053e-01 ... 5.53191489e-01
  1.00000000e+00 2.04470199e-01]
 [2.35697744e-04 0.00000000e+00 2.42302053e-01 ... 5.53191489e-01
  9.89737254e-01 6.34657837e-02]
 ...
 [6.11892474e-04 0.00000000e+00 4.20454545e-01 ... 8.93617021e-01
  1.00000000e+00 1.07891832e-01]
 [1.16072990e-03 0.00000000e+00 4.20454545e-01 ... 8.93617021e-01
  9.91300620e-01 1.31070640e-01]
 [4.61841693e-04 0.00000000e+00 4.20454545e-01 ... 8.93617021e-01
  1.00000000e+00 1.69701987e-01]]


In [57]:
m,n = X_norm.shape
a = 0.1
itr = 2000
lambda_reg = 1

In [58]:
#Ridge model


w_ridge = np.zeros(n)
b_ridge = 0


In [59]:
for i in range(itr):
    y_pred = np.dot(X_norm , w_ridge) + b_ridge
   

    error = y_pred - y


    dj_dw = (np.dot(X_norm.T, error) / m) + (lambda_reg * w_ridge) / m
    dj_db = np.sum(error) / m

    w_ridge -= a * dj_dw
    b_ridge -= a * dj_db


print("ridge w: ", w_ridge)
print("ridge b: ",b_ridge)

ridge w:  [ -4.88705559   3.17089221  -0.09380266   2.94944461  -4.98052031
  21.80388307   0.43006496  -9.73360919   4.60639246  -4.58494092
  -7.9597896    4.71598532 -17.4731761 ]
ridge b:  20.816233460897134


In [60]:
#lasso model


w_lasso = np.zeros(n)
b_lasso = 0

for i in range(itr):
    y_pred = np.dot(X_norm, w_lasso) + b_lasso

   
    error = y_pred - y


    dj_dw = (np.dot(X_norm.T, error) / m) + (lambda_reg * np.sign(w_lasso)) / m
    dj_db = np.sum(error) / m

    w_lasso -= a * dj_dw
    b_lasso -= a * dj_db
    

print("lasso w: ", w_lasso)
print("lasso b: ", b_lasso )    

lasso w:  [ -5.26833338   3.23683927   0.37158073   2.81079558  -5.34898068
  23.77606337   0.43478177 -10.60784587   4.99978493  -4.8831622
  -7.9790529    4.81494578 -18.00725071]
lasso b:  20.02369155591837


In [61]:
#comparision


ridge_mse = np.mean((np.dot(X_norm , w_ridge)+ b_ridge - y)**2)
lasso_mse = np.mean((np.dot(X_norm,w_lasso) +b_lasso - y)**2)


print("ridge mse: ", ridge_mse)
print("Lasso mse: ", lasso_mse)

ridge mse:  22.595727396094567
Lasso mse:  22.45419216999986
