In [75]:
import pandas as pd
import numpy as np


In [76]:
df = pd.read_csv("diabetes.csv")

In [77]:
X = df.drop(["Outcome"], axis = 1).values
y = df["Outcome"].values


y = np.where(y==0,-1,1)



In [78]:
def normalise(data):
    data_norm = (data - data.min(axis=0)) / (data.max(axis=0) - data.min(axis=0))
    return data_norm

X_norm = normalise(X)
print(X_norm)

[[0.35294118 0.74371859 0.59016393 ... 0.50074516 0.23441503 0.48333333]
 [0.05882353 0.42713568 0.54098361 ... 0.39642325 0.11656704 0.16666667]
 [0.47058824 0.91959799 0.52459016 ... 0.34724292 0.25362938 0.18333333]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]


In [79]:
m,n = X_norm.shape
a = 0.1
itr = 5000
lambda_reg = 0.01

w = np.zeros(n)
b = 0


for i in range(itr):

    dj_dw = lambda_reg*w
    dj_db = 0

    condition = y * (np.dot(X_norm, w) + b)


    for j in range(m):  
        if condition[j] < 1:
            dj_db -= y[j]
            
            dj_dw -= y[j] * X_norm[j]


    dj_dw = dj_dw/m
    dj_db = dj_db/m 

    w -= a*dj_dw
    b-= a*dj_db


In [80]:
print("SVM w: ", w)
print("SVM b: ", b)

SVM w:  [ 1.3801885   5.25732982 -1.12908898 -0.06345074 -0.14577585  2.9190204
  1.51403668  0.31269418]
SVM b:  -5.1852864583332785


In [81]:
y_hat = np.dot(X_norm, w) + b

y_final = np.sign(y_hat)


tp =0
fp=0
fn=0
tn=0


for j in range(m):
    if y_final[j] == 1 and y[j] ==1:
        tp+=1
    elif y_final[j] == 1 and y[j] == -1:
        fp+=1
    elif y_final[j] == -1 and y[j] == 1:
        fn+=1
    elif y_final[j] == -1 and y[j] == -1:
        tn+=1            



print(f"TP: {tp}, FP: {fp}, TN: {tn}, FN: {fn}")        

TP: 147, FP: 52, TN: 448, FN: 121


In [82]:
accuracy = (tp+tn)/m*100
precision = tp/(tp+fp) if(tp+fp) > 0 else 0
recall = tp/ (tp+fn) if (tp+fn ) > 0 else 0
f1_score = 2*(precision *recall) / (precision+recall) if (precision + recall) > 0 else 0




In [83]:

print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", f1_score)



Accuracy:  77.47395833333334
Precision:  0.7386934673366834
Recall:  0.5485074626865671
F1 Score:  0.6295503211991434
