In [ ]:
import pandas as pd
import numpy as np

data_frame = pd.read_csv("Boston.csv")
dataset = data_frame.to_numpy()
dataset

features_matrix = dataset[:, 1:14]
target_vector = dataset[:, 14]
print(features_matrix)
print(target_vector)

min_vals = np.min(features_matrix, axis=0)
max_vals = np.max(features_matrix, axis=0)
features_matrix = (features_matrix - min_vals) / (max_vals - min_vals)

num_samples, num_features = features_matrix.shape
learning_rate = 0.01
reg_factor = 1

weights_ridge = np.zeros(num_features)
bias_ridge = 0.0
weights_lasso = np.zeros(num_features)
bias_lasso = 0.0

for epoch in range(1000):
    predictions = np.dot(features_matrix, weights_ridge) + bias_ridge
    grad_w = np.zeros(num_features)
    grad_b = 0.0
    
    for row_idx in range(num_samples):
        error = predictions[row_idx] - target_vector[row_idx]
        grad_b += error
        for col_idx in range(num_features):
            grad_w[col_idx] += error * features_matrix[row_idx][col_idx]
            
    grad_w = (grad_w / num_samples) + (reg_factor * weights_ridge) / num_samples
    grad_b = grad_b / num_samples
    
    weights_ridge -= learning_rate * grad_w
    bias_ridge -= learning_rate * grad_b

for epoch in range(1000):
    predictions = np.dot(features_matrix, weights_lasso) + bias_lasso
    grad_w = np.zeros(num_features)
    grad_b = 0.0
    
    for row_idx in range(num_samples):
        error = predictions[row_idx] - target_vector[row_idx]
        grad_b += error
        for col_idx in range(num_features):
            grad_w[col_idx] += error * features_matrix[row_idx][col_idx]
            
    grad_w = (grad_w / num_samples) + (reg_factor * np.sign(weights_lasso)) / num_samples
    grad_b = grad_b / num_samples
    
    weights_lasso -= learning_rate * grad_w
    bias_lasso -= learning_rate * grad_b

outputs_ridge = np.dot(features_matrix, weights_ridge) + bias_ridge
outputs_lasso = np.dot(features_matrix, weights_lasso) + bias_lasso

mse_ridge = 0.0
mse_lasso = 0.0
for idx in range(num_samples):
    mse_ridge += (outputs_ridge[idx] - target_vector[idx]) ** 2
    mse_lasso += (outputs_lasso[idx] - target_vector[idx]) ** 2
    
mse_ridge /= num_samples
mse_lasso /= num_samples

print("Ridge MSE =", mse_ridge)
print("Lasso MSE =", mse_lasso)

columns = ["crim", "zn", "indus", "chas", "nox", "rm", "age", "dis", "rad", "tax", "ptratio", "black", "lstat"]
print("RIDGE COEFFICIENTS")
for i in range(num_features):
    print(columns[i], ":", weights_ridge[i])
print()
print("LASSO COEFFICIENTS")
for i in range(num_features):
    print(columns[i], ":", weights_lasso[i])

test_sample = np.array([0.00632, 18.0, 2.31, 0, 0.538, 6.575, 65.2, 4.09, 1, 296, 15.3, 396.9, 4.98])

test_sample = (test_sample - min_vals) / (max_vals - min_vals)

pred_val_ridge = np.dot(test_sample, weights_ridge) + bias_ridge
pred_val_lasso = np.dot(test_sample, weights_lasso) + bias_lasso

print("Ridge Prediction =", pred_val_ridge)
print("Lasso Prediction =", pred_val_lasso)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.