In [125]:
import numpy as np
import pandas as pd
db=pd.read_csv("insurance.csv")
db=db.replace({"male":0,"female":1,"yes":1,"no":0,"southwest":1,"southeast":2,"northwest":3,"northeast":0})
db=db.values
db


array([[19, 1, 27.9, ..., 1, 1, 16884.92],
       [18, 0, 33.8, ..., 0, 2, 1725.55],
       [28, 0, 33.0, ..., 0, 2, 4449.46],
       ...,
       [18, 1, 36.9, ..., 0, 2, 1629.83],
       [21, 1, 25.8, ..., 0, 1, 2007.95],
       [61, 1, 29.1, ..., 1, 3, 29141.36]], shape=(1338, 7), dtype=object)

In [126]:
x=db[:,:6]
y=db[:,6]
print(x)
print(y)


[[19 1 27.9 0 1 1]
 [18 0 33.8 1 0 2]
 [28 0 33.0 3 0 2]
 ...
 [18 1 36.9 0 0 2]
 [21 1 25.8 0 0 1]
 [61 1 29.1 0 1 3]]
[16884.92 1725.55 4449.46 ... 1629.83 2007.95 29141.36]


In [127]:
x_min=x.min(axis=0)
x_max=x.max(axis=0)
x=(x-x_min)/(x_max-x_min)
print(x)

[[0.021739130434782608 1.0 0.320754716981132 0.0 1.0 0.3333333333333333]
 [0.0 0.0 0.47978436657681933 0.2 0.0 0.6666666666666666]
 [0.21739130434782608 0.0 0.4582210242587601 0.6 0.0 0.6666666666666666]
 ...
 [0.0 1.0 0.5633423180592991 0.0 0.0 0.6666666666666666]
 [0.06521739130434782 1.0 0.2641509433962264 0.0 0.0 0.3333333333333333]
 [0.9347826086956522 1.0 0.3530997304582211 0.0 1.0 1.0]]


In [128]:
y_min=y.min()
y_max=y.max()
y=(y-y_min)/(y_max-y_min)
print(y)

[0.25161073135599604 0.009635975671268423 0.053115187324337544 ...
 0.008108087400572336 0.01414366108335132 0.4472487476168647]


In [129]:
m,n=x.shape
w=np.zeros(n)
b=0
a=0.1

In [130]:
for k in range(1000):
    f_wb=np.dot(x,w)+b
    for j in range(n):
        dj_dw=0
        dj_db=0
        for  i in range(m):
            dj_dw+=(f_wb[i]-y[i])*x[i][j]
            dj_db+=f_wb[i]-y[i]
        dj_dw=dj_dw/m
        dj_db=dj_db/m
        w[j]-=a*dj_dw
    b-=a*dj_db
    

In [131]:
print(w)
b

[ 0.18930036  0.00129357  0.17305861  0.03690728  0.37990621 -0.00570786]


-0.04520648504804247

In [132]:
test=[19,1,27.9,0,1,1]

In [133]:
test=(test-x_min) / (x_max - x_min)
insuranceprediction=np.dot(test,w)+b
insuranceprediction=insuranceprediction*(y_max-y_min)+y_min
print("Prediction for provided test is:",insuranceprediction)

Prediction for provided test is: 25787.564585478543
