In [15]:
import numpy as np
import pandas as pd

In [16]:
df=pd.read_csv("Boston.csv")
df=df.values
df

array([[1.0000e+00, 6.3200e-03, 1.8000e+01, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.0000e+00, 2.7310e-02, 0.0000e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [3.0000e+00, 2.7290e-02, 0.0000e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [5.0400e+02, 6.0760e-02, 0.0000e+00, ..., 3.9690e+02, 5.6400e+00,
        2.3900e+01],
       [5.0500e+02, 1.0959e-01, 0.0000e+00, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [5.0600e+02, 4.7410e-02, 0.0000e+00, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01]], shape=(506, 15))

In [17]:
x=df[:,1:14]
y=df[:,14]
print(x)
print(y)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

In [18]:
x_min=np.min(x,axis=0)
x_max=np.max(x,axis=0)
x=(x-x_min)/(x_max-x_min)

In [19]:
m,n=x.shape
a=0.01
lambda_reg=1
w_ridge=np.zeros(n)
b_ridge=0
w_lasso=np.zeros(n)
b_lasso=0

In [20]:
for i in range(1000):
    prediction=np.dot(x,w_ridge)+b_ridge
    dj_dw=np.zeros(n)
    dj_db=0
    for j in range(m):
        dj_db+=(prediction[j]-y[j])
        for k in range(n):
            dj_dw[k]+=(prediction[j]-y[j])*x[j][k]
    dj_dw=(dj_dw/m)+(lambda_reg*w_ridge)/m
    dj_db=dj_db/m
    w_ridge-=a*dj_dw
    b_ridge-=a*dj_db

In [21]:
for i in range(1000):
    y_pred=np.dot(x,w_lasso)+b_lasso
    dj_dw=np.zeros(n)
    dj_db=0
    for j in range(m):
        dj_db+=(y_pred[j]-y[j])
        for k in range(n):
            dj_dw[k]+=(y_pred[j]-y[j])*x[j][k]
    dj_dw=(dj_dw/m)+(lambda_reg*np.sign(w_lasso))/m
    dj_db=dj_db/m
    w_lasso-=a*dj_dw
    b_lasso-=a*dj_db

In [22]:
ridge_pred=np.dot(x,w_ridge)+b_ridge
lasso_pred=np.dot(x,w_lasso)+b_lasso

In [23]:
ridge_mse=0
lasso_mse=0
for i in range(m):
    ridge_mse+=(ridge_pred[i]-y[i])**2
    lasso_mse+=(lasso_pred[i]-y[i])**2
ridge_mse=ridge_mse/m
lasso_mse=lasso_mse/m
print("Ridge MSE =",ridge_mse)
print("Lasso MSE =",lasso_mse)
#we can see lasso is better

Ridge MSE = 42.272969972078165
Lasso MSE = 42.16862068692723


In [24]:
features=["crim","zn","indus","chas","nox","rm","age","dis","rad","tax","ptratio","black","lstat"]
print("RIDGE COEFFICIENTS")
for i in range(n):
    print(features[i],":",w_ridge[i])
print()
print("LASSO COEFFICIENTS")
for i in range(n):
    print(features[i],":",w_lasso[i])

RIDGE COEFFICIENTS
crim : -1.2364305009552068
zn : 4.418036955633836
indus : -1.4365448913381964
chas : 3.0597202103473444
nox : -0.5893480529042222
rm : 10.973664201253218
age : 1.5738073701674455
dis : 2.901834706026733
rad : -1.1011524482446295
tax : -2.014821045535172
ptratio : -1.2249771528052564
black : 9.553623966111433
lstat : -5.370797524650213

LASSO COEFFICIENTS
crim : -1.2302030106192436
zn : 4.438082831098542
indus : -1.4392020093308655
chas : 3.070156237488189
nox : -0.5863234838423812
rm : 11.057336373553925
age : 1.5708870535228565
dis : 2.907764956295575
rad : -1.0965322847860808
tax : -2.020730787955616
ptratio : -1.2427495551835812
black : 9.614761590640304
lstat : -5.405948901056974


In [25]:
test=np.array([0.00632,18.0,2.31,0,0.538,6.575,65.2,4.09,1,296,15.3,396.9,4.98])

In [26]:

test=(test-x_min)/(x_max-x_min)

ridge_value=np.dot(test,w_ridge)+b_ridge
lasso_value=np.dot(test,w_lasso)+b_lasso

print("Ridge Prediction =",ridge_value)
print("Lasso Prediction =",lasso_value)

Ridge Prediction = 26.979092716122214
Lasso Prediction = 27.0130160847756
