In [36]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [37]:
df=pd.read_csv("diabetes.csv")
df=df.values
df

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]],
      shape=(768, 9))

In [38]:
x=df[:,:8]
y=df[:,8]
print(x)
y

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [39]:
for i in range(len(y)):
    if y[i]==0:
        y[i]=-1

In [40]:
x_min=np.min(x,axis=0)
x_max=np.max(x,axis=0)
x=(x-x_min)/(x_max-x_min)
x

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]], shape=(768, 8))

In [41]:
m,n=x.shape
w=np.zeros(n)
b=0
a=0.001
lambda_reg=0.01

In [42]:
for k in range(1000):
    for i in range(m):
        f_wb=np.dot(x[i],w)+b
        if y[i]*f_wb>=1:
            for j in range(n):
                w[j]=w[j]-a*(2*lambda_reg*w[j])
        else:
            for j in range(n):
                w[j]=w[j]-a*(2*lambda_reg*w[j]-y[i]*x[i][j])
            b=b+a*y[i]

In [43]:
prediction=np.zeros(m)

for i in range(m):

    f_wb=np.dot(x[i],w)+b

    if f_wb>=0:
        prediction[i]=1
    else:
        prediction[i]=-1

In [44]:
correct=0
for i in range(m):
    if prediction[i]==y[i]:
        correct+=1
accuracy=(correct/m)*100
print("Accuracy =",accuracy)

Accuracy = 65.625


In [45]:
features=["Pregnancies","Glucose","BloodPressure","SkinThickness","Insulin","BMI","DiabetesPedigreeFunction","Age"]
for i in range(n):
    print(features[i],":",w[i])

Pregnancies : 0.5463207784213736
Glucose : 1.4551459399783395
BloodPressure : -0.13982453091345456
SkinThickness : 0.11108992144599729
Insulin : 0.137334923620079
BMI : 0.6420906649163322
DiabetesPedigreeFunction : 0.47780723719959256
Age : 0.34109142765922756


In [46]:
test=np.array([6,148,72,35,0,33.6,0.627,50])

In [47]:
test=(test-x_min)/(x_max-x_min)
prediction=model.predict([test])

if prediction[0]==1:
    print("Diabetic")
else:
    print("Non-Diabetic")

Diabetic
